fix(take): do not consume one extra element than specified
vitaly-t/iter-ops pull request #224
Opened 2023-07-17 21:22 UTC by crossing

Currently `take` consumes one extra element before finishing up. The check `index >= count` should be done before consuming next element.

2023-07-17 22:21 UTC, RebeccaStevens approved these changes

2023-07-19 11:44 UTC, vitaly-t commented
@crossing If this issue+change is valid, then it means that a test is missing [here](https://github.com/vitaly-t/iter-ops/tree/main/test/ops/take). Please include the missing test for this change, one that fails before the change, and passes after the change. Thank you!

2023-07-19 11:45 UTC, vitaly-t requested changes
Please add the missing test(s).

2023-07-19 11:45 UTC, vitaly-t commented on src/ops/take.ts
Reviewed the change, need the missing tests for it, as per previous comments.

2023-07-19 20:31 UTC, crossing commented on src/ops/take.ts
I don't currently have enough spare time to setup a full environment for this project and add the test case. I'll try but it'll take time. Feel free to take it over in the mean time.

2023-07-19 20:33 UTC, crossing commented on src/ops/take.ts
I'd imaging a test is something along the line of:
```
const iter = <something generating 1...10>

pipe(iter, take(3))  -> expecting 1,2,3
pipe(iter, take(3)) -> expecting 4,5,6: this part would fail previously
```

2023-07-23 12:59 UTC, merged

2023-07-23 13:56 UTC, vitaly-t commented
@crossing [v3.1.0](https://github.com/vitaly-t/iter-ops/releases/tag/3.1.0) was released with the fix. Thanks for your help!